# Generated by Django 3.1.6 on 2021-04-09 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coworking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_round_the_clock', models.BooleanField(null=True, verbose_name='Круглосуточно')),
                ('regular_start', models.TimeField(null=True, verbose_name='Начало работы')),
                ('regular_end', models.TimeField(null=True, verbose_name='Конец работы')),
                ('regular_start2', models.TimeField(null=True, verbose_name='Начало работы в специальные дни')),
                ('regular_end2', models.TimeField(null=True, verbose_name='Конец работы в специальные дни')),
                ('days_for_regular2', models.CharField(max_length=150, verbose_name='Специальные дни')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Времена работы',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.TextField(verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.FloatField(verbose_name='Цена за час, р'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coworking.place', verbose_name='Место')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(null=True, verbose_name='Начало работы')),
                ('end', models.TimeField(null=True, verbose_name='Конец работы')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coworking.reservation', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Забронированное время',
                'verbose_name_plural': 'Забронированные часы',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='available_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coworking.availabletime', verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.categories', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='place',
            name='services',
            field=models.ManyToManyField(to='coworking.Services'),
        ),
    ]
