# Generated by Django 3.2 on 2021-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0002_auto_20210427_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtime',
            name='end',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='bookedtime',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Начало'),
        ),
    ]
