# Generated by Django 3.1.6 on 2021-04-09 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coworking', '0003_auto_20210409_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtime',
            name='end',
            field=models.TimeField(null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='bookedtime',
            name='start',
            field=models.TimeField(null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.place', verbose_name='Место')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
