# Generated by Django 3.2 on 2021-05-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0003_auto_20210517_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedtime',
            name='end',
        ),
        migrations.RemoveField(
            model_name='bookedtime',
            name='start',
        ),
    ]
