# Generated by Django 3.2 on 2021-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0004_auto_20210518_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtime',
            name='end',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='bookedtime',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Начало'),
        ),
    ]
