# Generated by Django 3.1.6 on 2021-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0005_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='place',
            name='services',
            field=models.ManyToManyField(to='coworking.Services'),
        ),
    ]
