# Generated by Django 3.2 on 2021-05-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0005_auto_20210518_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booked',
        ),
    ]
