# Generated by Django 3.1.6 on 2021-04-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210416_2247'),
        ('coworking', '0005_auto_20210416_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.equipment', verbose_name='Оснащение'),
        ),
        migrations.AddField(
            model_name='place',
            name='uniqueQualities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.uniquequalities', verbose_name='Уникальные качества'),
        ),
    ]
