# Generated by Django 3.1.6 on 2021-04-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0006_auto_20210407_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_round_the_clock', models.BooleanField()),
                ('regular_start', models.TimeField()),
                ('regular_end', models.TimeField()),
                ('regular_start2', models.TimeField()),
                ('regular_end2', models.TimeField()),
                ('days_for_regular2', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Времена работы',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='available_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.availabletime', verbose_name='Время работы'),
        ),
    ]
