# Generated by Django 3.2 on 2021-05-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0006_remove_reservation_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedtime',
            name='end',
        ),
        migrations.RemoveField(
            model_name='bookedtime',
            name='start',
        ),
    ]
