# Generated by Django 3.1.6 on 2021-04-16 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coworking', '0007_place_freeservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Группа людей')),
            ],
            options={
                'verbose_name': 'Группа людей',
                'verbose_name_plural': 'Группы людей',
            },
        ),
    ]
