# Generated by Django 3.1.6 on 2021-04-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0008_auto_20210408_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='available_time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.availabletime', verbose_name='Время работы'),
        ),
    ]
