# Generated by Django 3.2 on 2021-05-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0009_auto_20210518_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.bookedtime', verbose_name='Время'),
        ),
    ]
