# Generated by Django 3.2 on 2021-05-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0010_reservation_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.place', verbose_name='Место'),
        ),
    ]
