# Generated by Django 3.1.6 on 2021-04-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0010_auto_20210408_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(null=True, verbose_name='Начало работы')),
                ('end', models.TimeField(null=True, verbose_name='Конец работы')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coworking.place', verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Забронированное время',
                'verbose_name_plural': 'Забронированные часы',
            },
        ),
    ]
