# Generated by Django 3.1.6 on 2021-04-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0011_bookedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtime',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coworking.place', verbose_name='Место'),
        ),
    ]
