# Generated by Django 3.1.6 on 2021-04-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(verbose_name='Площадь, м2')),
                ('free_spaces', models.IntegerField(verbose_name='Количество свободных мест')),
                ('conference_hall', models.BooleanField(verbose_name='Наличие конференц зала')),
            ],
            options={
                'verbose_name': 'Оснащение',
                'verbose_name_plural': 'Оснащения',
            },
        ),
        migrations.CreateModel(
            name='UniqueQualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=150, verbose_name='Качество')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уникальное качество',
                'verbose_name_plural': 'Уникальные качества',
            },
        ),
        migrations.AlterField(
            model_name='freeservices',
            name='free_tea',
            field=models.BooleanField(verbose_name='Бесплатный чай'),
        ),
        migrations.AlterField(
            model_name='freeservices',
            name='free_wifi',
            field=models.BooleanField(verbose_name='Бесплатный wi-fi'),
        ),
        migrations.AlterField(
            model_name='freeservices',
            name='parking_spaces',
            field=models.BooleanField(verbose_name='Свободные парковочные места'),
        ),
    ]
